version: '3'

services:
  backend:
    build: ./actividad-tecnica-php  # path to the directory containing the Dockerfile
    command: node server.js 
    ports:
      - "3002:3002"
    depends_on:
      - db

  frontend:
    build: ./actividad-tecnica-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: comentarios_db
    ports:
      - "3307:3306"
