version: '3'

services:

  backend:
    build: 
      context: ./actividad-tecnica-php
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: comentarios_db
      DB_USERNAME: root
      DB_PASSWORD: 1234

  frontend:
    build: ./actividad-tecnica-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: comentarios_db
    ports:
      - "3307:3306"
